#!/usr/bin/perl
# Generate Rust tag tables from ExifTool Perl source.
# Usage: perl scripts/gen_tags.pl /path/to/exiftool/lib > src/tags/generated.rs

use strict;
use warnings;

my $lib_dir = $ARGV[0] || '../exiftool/lib';
my $exif_pm = "$lib_dir/Image/ExifTool/Exif.pm";

die "Cannot find $exif_pm" unless -f $exif_pm;

print "//! Auto-generated EXIF tag tables from ExifTool Perl source.\n";
print "//! Generated by scripts/gen_tags.pl\n";
print "//! DO NOT EDIT MANUALLY.\n\n";

# Parse Exif.pm for all tag definitions
open my $fh, '<', $exif_pm or die "Cannot open $exif_pm: $!";
my $content = do { local $/; <$fh> };
close $fh;

# Extract tag entries: 0xNNNN => { Name => 'XXX', ... }
my @tags;
while ($content =~ /^\s+(0x[0-9a-fA-F]+)\s*=>\s*\{(.*?)\}/gms) {
    my $hex = $1;
    my $body = $2;

    my ($name) = $body =~ /Name\s*=>\s*['"](\w+)['"]/;
    next unless $name;

    my $desc = $name;
    $desc =~ s/([a-z])([A-Z])/$1 $2/g;

    my $f2 = 'Image';
    $f2 = 'Camera' if $name =~ /^(Make|Model|Lens|Serial|Owner|Body|Firmware|ISO|Exposure|Aperture|Shutter|Focus|Flash|Meter|WhiteBalance|Saturation|Contrast|Sharpness|DigitalZoom|SceneCapture|Gain|NoiseReduction|Sensitivity|Custom)/i;
    $f2 = 'Time' if $name =~ /Date|Time/i;
    $f2 = 'Location' if $name =~ /GPS/i;
    $f2 = 'Author' if $name =~ /Artist|Copyright|Author|Owner/i;

    push @tags, { hex => $hex, name => $name, desc => $desc, f2 => $f2 };
}

# Print tag count
my $count = scalar @tags;
print "/// Total tags extracted: $count\n\n";

print "pub struct GenTagInfo {\n";
print "    pub tag_id: u16,\n";
print "    pub name: &'static str,\n";
print "    pub description: &'static str,\n";
print "    pub family2: &'static str,\n";
print "}\n\n";

print "pub static GENERATED_EXIF_TAGS: &[GenTagInfo] = &[\n";
for my $t (sort { hex($a->{hex}) <=> hex($b->{hex}) } @tags) {
    printf "    GenTagInfo { tag_id: %s, name: \"%s\", description: \"%s\", family2: \"%s\" },\n",
        $t->{hex}, $t->{name}, $t->{desc}, $t->{f2};
}
print "];\n\n";

# Also extract from Canon.pm, Nikon.pm, Sony.pm main tag tables
for my $module (qw(Canon Nikon Sony Olympus Pentax Panasonic FujiFilm Samsung)) {
    my $pm_file = "$lib_dir/Image/ExifTool/$module.pm";
    next unless -f $pm_file;

    open my $mfh, '<', $pm_file or next;
    my $mcontent = do { local $/; <$mfh> };
    close $mfh;

    my @mtags;
    while ($mcontent =~ /^\s+(0x[0-9a-fA-F]+)\s*=>\s*\{(.*?)\}/gms) {
        my $hex = $1;
        my $body = $2;
        my ($name) = $body =~ /Name\s*=>\s*['"](\w+)['"]/;
        next unless $name;
        push @mtags, { hex => $hex, name => $name };
    }

    next unless @mtags;

    my $var_name = uc($module) . "_TAGS";
    printf "/// %s MakerNotes tags: %d\n", $module, scalar @mtags;
    printf "pub static GENERATED_%s: &[(u16, &str)] = &[\n", $var_name;
    for my $t (sort { hex($a->{hex}) <=> hex($b->{hex}) } @mtags) {
        printf "    (%s, \"%s\"),\n", $t->{hex}, $t->{name};
    }
    print "];\n\n";
}

print "// End of auto-generated tags\n";
