#!/usr/bin/perl
# Extract MakerNotes binary sub-table definitions from ExifTool Perl source.
# Generates Rust decoders for int16s/int16u arrays (CameraSettings, ShotInfo, etc.)
#
# Usage: perl scripts/gen_sub_tables.pl /path/to/exiftool/lib > src/tags/sub_tables_generated.rs

use strict;
use warnings;
use File::Find;

my $lib_dir = $ARGV[0] || '../exiftool/lib';
die "Cannot find $lib_dir" unless -d $lib_dir;

my @modules = qw(Canon Nikon Sony Olympus Pentax Panasonic FujiFilm Samsung);
my @all_tables;
my %seen_fn;
my $total_fields = 0;

for my $module (@modules) {
    my $file = "$lib_dir/Image/ExifTool/$module.pm";
    next unless -f $file;

    open my $fh, '<', $file or next;
    my $content = do { local $/; <$fh> };
    close $fh;

    # Find binary sub-tables: tables with FIRST_ENTRY and Format => 'int16s' etc.
    # Pattern: %Image::ExifTool::Module::TableName = ( ... FIRST_ENTRY => N, ... )
    while ($content =~ /(%Image::ExifTool::${module}::(\w+))\s*=\s*\((.*?)\n\);/gs) {
        my $full_name = $1;
        my $table_name = $2;
        my $body = $3;

        # Skip empty or problematic table names
        next unless $table_name && length($table_name) > 1 && $table_name =~ /^[A-Za-z]\w{1,}$/;
        # Skip Main table (handled separately)
        next if $table_name eq 'Main';
        # Skip tables that would generate invalid function names
        next if $table_name =~ /^\d/;

        # Check if this is a binary data table
        next unless $body =~ /FIRST_ENTRY/;

        my ($first_entry) = $body =~ /FIRST_ENTRY\s*=>\s*(\d+)/;
        $first_entry ||= 0;

        my ($format) = $body =~ /FORMAT\s*=>\s*'(\w+)'/;
        $format ||= 'int16s';

        # Extract field definitions: INDEX => { Name => 'FieldName', ... }
        my @fields;
        while ($body =~ /(\d+)\s*=>\s*\{((?:[^{}]|\{(?:[^{}]|\{[^{}]*\})*\})*)\}/g) {
            my $index = int($1);
            my $field_body = $2;

            my ($name) = $field_body =~ /Name\s*=>\s*['"](\w+)['"]/;
            next unless $name;

            # Check for PrintConv hash
            my %conv;
            if ($field_body =~ /PrintConv\s*=>\s*\{([^}]+)\}/) {
                my $conv_str = $1;
                while ($conv_str =~ /(-?\d+|0x[0-9a-fA-F]+)\s*=>\s*['"]([^'"]*)['"]/g) {
                    my $k = $1;
                    if ($k =~ /^0x/) { $k = hex($k); }
                    $conv{int($k)} = $2;
                }
            }

            # Check for RawConv/ValueConv that makes value undef
            my $skip_undef = 0;
            if ($field_body =~ /RawConv.*undef|Condition.*0/) {
                $skip_undef = 1;
            }

            # Check for custom Format override
            my ($field_format) = $field_body =~ /Format\s*=>\s*'(\w+)'/;

            push @fields, {
                index => $index,
                name => $name,
                conv => \%conv,
                format => $field_format,
                skip_undef => $skip_undef,
            };
        }

        next unless @fields;

        # Deduplicate: skip if we already have this function name
        my $fn_key = lc("${module}_${table_name}");
        next if $seen_fn{$fn_key}++;


        push @all_tables, {
            module => $module,
            table_name => $table_name,
            first_entry => $first_entry,
            format => $format,
            fields => \@fields,
        };
        $total_fields += scalar @fields;
    }
}

# Generate Rust code
print "//! Auto-generated MakerNotes sub-table decoders.\n";
print "//! Generated by scripts/gen_sub_tables.pl\n";
print "//! Total: " . scalar(@all_tables) . " tables with $total_fields fields.\n";
print "//! DO NOT EDIT MANUALLY.\n\n";

print "use crate::tag::{Tag, TagGroup, TagId};\n";
print "use crate::value::Value;\n\n";

# Generate a dispatcher function
print "/// Decode a MakerNotes binary sub-table.\n";
print "/// `module` is the manufacturer name, `table` is the sub-table name.\n";
print "/// `data` is the raw binary data, `byte_order_le` indicates little-endian.\n";
print "pub fn decode_sub_table(\n";
print "    module: &str,\n";
print "    table: &str,\n";
print "    data: &[u8],\n";
print "    byte_order_le: bool,\n";
print ") -> Vec<Tag> {\n";
print "    match (module, table) {\n";

for my $t (@all_tables) {
    printf "        (\"%s\", \"%s\") => decode_%s_%s(data, byte_order_le),\n",
        $t->{module}, $t->{table},
        lc($t->{module}), lc($t->{table});
}

print "        _ => Vec::new(),\n";
print "    }\n";
print "}\n\n";

# Generate individual decoder functions
for my $t (@all_tables) {
    my $fn_name = sprintf "decode_%s_%s", lc($t->{module}), lc($t->{table});
    my $is_signed = $t->{format} =~ /int16s|int32s/;
    my $is_32bit = $t->{format} =~ /int32/;
    my $elem_size = $is_32bit ? 4 : 2;

    printf "fn %s(data: &[u8], le: bool) -> Vec<Tag> {\n", $fn_name;
    print "    let mut tags = Vec::new();\n";

    # Generate read helper
    if ($is_32bit) {
        if ($is_signed) {
            print "    let rd = |i: usize| -> i32 {\n";
            print "        let o = i * 4; if o + 4 > data.len() { return 0; }\n";
            print "        if le { i32::from_le_bytes([data[o],data[o+1],data[o+2],data[o+3]]) }\n";
            print "        else { i32::from_be_bytes([data[o],data[o+1],data[o+2],data[o+3]]) }\n";
            print "    };\n";
        } else {
            print "    let rd = |i: usize| -> u32 {\n";
            print "        let o = i * 4; if o + 4 > data.len() { return 0; }\n";
            print "        if le { u32::from_le_bytes([data[o],data[o+1],data[o+2],data[o+3]]) }\n";
            print "        else { u32::from_be_bytes([data[o],data[o+1],data[o+2],data[o+3]]) }\n";
            print "    };\n";
        }
    } else {
        if ($is_signed) {
            print "    let rd = |i: usize| -> i16 {\n";
            print "        let o = i * 2; if o + 2 > data.len() { return 0; }\n";
            print "        if le { i16::from_le_bytes([data[o],data[o+1]]) }\n";
            print "        else { i16::from_be_bytes([data[o],data[o+1]]) }\n";
            print "    };\n";
        } else {
            print "    let rd = |i: usize| -> u16 {\n";
            print "        let o = i * 2; if o + 2 > data.len() { return 0; }\n";
            print "        if le { u16::from_le_bytes([data[o],data[o+1]]) }\n";
            print "        else { u16::from_be_bytes([data[o],data[o+1]]) }\n";
            print "    };\n";
        }
    }

    for my $f (sort { $a->{index} <=> $b->{index} } @{$t->{fields}}) {
        my $idx = $f->{index};
        my $name = $f->{name};
        my %conv = %{$f->{conv}};

        if (%conv && scalar(keys %conv) >= 2 && scalar(keys %conv) <= 50) {
            # PrintConv available - generate match
            printf "    { let v = rd(%d); let s = match v as i64 {\n", $idx;
            for my $k (sort { $a <=> $b } keys %conv) {
                my $val = $conv{$k};
                $val =~ s/\\/\\\\/g;
                $val =~ s/"/\\"/g;
                printf "        %d => \"%s\",\n", $k, $val;
            }
            print "        _ => \"\",\n";
            print "    };\n";
            printf "    if !s.is_empty() { tags.push(mk(\"%s\", \"%s\", s, \"%s\")); } }\n",
                $t->{module}, $name, $name;
        } else {
            # Numeric value
            if ($is_signed) {
                printf "    { let v = rd(%d); if v != 0 { tags.push(mkn(\"%s\", \"%s\", v as i32)); } }\n",
                    $idx, $t->{module}, $name;
            } else {
                printf "    { let v = rd(%d); if v != 0 { tags.push(mkn(\"%s\", \"%s\", v as i32)); } }\n",
                    $idx, $t->{module}, $name;
            }
        }
    }

    print "    tags\n";
    print "}\n\n";
}

# Helper functions
print "fn mk(module: &str, name: &str, value: &str, desc: &str) -> Tag {\n";
print "    Tag {\n";
print "        id: TagId::Text(name.to_string()),\n";
print "        name: name.to_string(),\n";
print "        description: desc.to_string(),\n";
print "        group: TagGroup {\n";
print "            family0: \"MakerNotes\".into(),\n";
print "            family1: module.into(),\n";
print "            family2: \"Camera\".into(),\n";
print "        },\n";
print "        raw_value: Value::String(value.to_string()),\n";
print "        print_value: value.to_string(),\n";
print "        priority: 0,\n";
print "    }\n";
print "}\n\n";

print "fn mkn(module: &str, name: &str, value: i32) -> Tag {\n";
print "    Tag {\n";
print "        id: TagId::Text(name.to_string()),\n";
print "        name: name.to_string(),\n";
print "        description: name.to_string(),\n";
print "        group: TagGroup {\n";
print "            family0: \"MakerNotes\".into(),\n";
print "            family1: module.into(),\n";
print "            family2: \"Camera\".into(),\n";
print "        },\n";
print "        raw_value: Value::I32(value),\n";
print "        print_value: value.to_string(),\n";
print "        priority: 0,\n";
print "    }\n";
print "}\n";

warn sprintf "Generated %d tables with %d fields from %d modules\n",
    scalar(@all_tables), $total_fields, scalar(@modules);
