#!/usr/bin/perl
# Extract ALL PrintConv hash tables from ExifTool Perl source.
# Generates Rust code with lookup functions.
#
# Usage: perl scripts/gen_print_conv.pl /path/to/exiftool/lib > src/tags/print_conv_generated.rs

use strict;
use warnings;
use File::Find;

my $lib_dir = $ARGV[0] || '../exiftool/lib';
die "Cannot find $lib_dir" unless -d $lib_dir;

# Collect all .pm files
my @pm_files;
find(sub { push @pm_files, $File::Find::name if /\.pm$/ }, "$lib_dir/Image/ExifTool");
@pm_files = sort @pm_files;

# Storage for all extracted conversions
# Key: "Module::TagID" => { value => "string", ... }
my %all_convs;
my %tag_names; # TagID => Name mapping per module

my $total_entries = 0;
my $total_tags = 0;

for my $file (@pm_files) {
    open my $fh, '<', $file or next;
    my $content = do { local $/; <$fh> };
    close $fh;

    # Extract module name from filename
    my ($module) = $file =~ m{/(\w+)\.pm$};
    next unless $module;

    # Strategy: find tag entries with PrintConv => { ... }
    # We look for patterns like:
    #   0xNNNN => {
    #       Name => 'TagName',
    #       PrintConv => {
    #           N => 'String',
    #           ...
    #       },
    #   },

    # Find all tag definitions with PrintConv hashes
    while ($content =~ /
        (0x[0-9a-fA-F]+|[\d]+)\s*=>\s*\{   # tag ID
        ((?:[^{}]|\{(?:[^{}]|\{[^{}]*\})*\})*)  # tag body (nested braces)
        \}/gx) {

        my $tag_hex = $1;
        my $body = $2;

        # Get tag name
        my ($name) = $body =~ /Name\s*=>\s*['"](\w+)['"]/;
        next unless $name;

        # Get tag ID as number
        my $tag_id;
        if ($tag_hex =~ /^0x/) {
            $tag_id = hex($tag_hex);
        } else {
            $tag_id = int($tag_hex);
        }
        next if $tag_id > 0xFFFF;

        # Find PrintConv hash (not subroutine)
        if ($body =~ /PrintConv\s*=>\s*\{([^}]+)\}/) {
            my $conv_body = $1;
            my %conv;

            # Parse key => 'value' pairs
            while ($conv_body =~ /(-?\d+|0x[0-9a-fA-F]+)\s*=>\s*['"]([^'"]*)['"]/g) {
                my $key = $1;
                my $val = $2;
                if ($key =~ /^0x/) {
                    $key = hex($key);
                }
                $conv{int($key)} = $val;
            }

            next unless %conv;

            my $conv_key = "${module}::${tag_id}";
            $all_convs{$conv_key} = {
                module => $module,
                tag_id => $tag_id,
                tag_name => $name,
                conv => \%conv,
            };
            $total_entries += scalar keys %conv;
            $total_tags++;
        }

        # Also handle PrintConv that references a named hash
        # PrintConv => \%hashName
        if ($body =~ /PrintConv\s*=>\s*\\%(\w+)/) {
            my $hash_name = $1;
            # Try to find the hash definition in the same file
            if ($content =~ /\%${hash_name}\s*=\s*\(([^;]+)\);/s) {
                my $hash_body = $1;
                my %conv;
                while ($hash_body =~ /(-?\d+|0x[0-9a-fA-F]+)\s*=>\s*['"]([^'"]*)['"]/g) {
                    my $key = $1;
                    my $val = $2;
                    if ($key =~ /^0x/) { $key = hex($key); }
                    $conv{int($key)} = $val;
                }
                if (%conv) {
                    my $conv_key = "${module}::${tag_id}";
                    $all_convs{$conv_key} = {
                        module => $module,
                        tag_id => $tag_id,
                        tag_name => $name,
                        conv => \%conv,
                    };
                    $total_entries += scalar keys %conv;
                    $total_tags++;
                }
            }
        }
    }
}

# Generate Rust code
print "//! Auto-generated PrintConv tables from ExifTool Perl source.\n";
print "//! Generated by scripts/gen_print_conv.pl\n";
print "//! Total: $total_tags tags with $total_entries conversion entries.\n";
print "//! DO NOT EDIT MANUALLY.\n\n";

# Group by module
my %by_module;
for my $key (sort keys %all_convs) {
    my $info = $all_convs{$key};
    push @{$by_module{$info->{module}}}, $info;
}

# Generate a single lookup function
print "/// Look up print conversion for a tag value.\n";
print "/// Returns the human-readable string for the given module, tag ID, and numeric value.\n";
print "pub fn print_conv(module: &str, tag_id: u16, value: i64) -> Option<&'static str> {\n";
print "    match (module, tag_id) {\n";

for my $module (sort keys %by_module) {
    my @tags = @{$by_module{$module}};
    for my $tag (sort { $a->{tag_id} <=> $b->{tag_id} } @tags) {
        my %conv = %{$tag->{conv}};
        my @keys = sort { $a <=> $b } keys %conv;

        # Skip very large tables (>100 entries) and tables with only negative keys
        next if scalar @keys > 100;
        next if scalar @keys < 2;

        printf "        (\"%s\", 0x%04X) => match value { // %s\n",
            $module, $tag->{tag_id}, $tag->{tag_name};

        for my $k (@keys) {
            my $v = $conv{$k};
            $v =~ s/\\/\\\\/g;
            $v =~ s/"/\\"/g;
            printf "            %d => Some(\"%s\"),\n", $k, $v;
        }
        print "            _ => None,\n";
        print "        },\n";
    }
}

print "        _ => None,\n";
print "    }\n";
print "}\n\n";

# Also generate a module-agnostic lookup by tag name
print "/// Look up print conversion by tag name and numeric value.\n";
print "pub fn print_conv_by_name(tag_name: &str, value: i64) -> Option<&'static str> {\n";
print "    match tag_name {\n";

my %by_name;
for my $key (sort keys %all_convs) {
    my $info = $all_convs{$key};
    my %conv = %{$info->{conv}};
    next if scalar(keys %conv) > 100 || scalar(keys %conv) < 2;
    $by_name{$info->{tag_name}} = $info unless exists $by_name{$info->{tag_name}};
}

for my $name (sort keys %by_name) {
    my $tag = $by_name{$name};
    my %conv = %{$tag->{conv}};
    my @keys = sort { $a <=> $b } keys %conv;

    printf "        \"%s\" => match value {\n", $name;
    for my $k (@keys) {
        my $v = $conv{$k};
        $v =~ s/\\/\\\\/g;
        $v =~ s/"/\\"/g;
        printf "            %d => Some(\"%s\"),\n", $k, $v;
    }
    print "            _ => None,\n";
    print "        },\n";
}

print "        _ => None,\n";
print "    }\n";
print "}\n";

warn "Extracted $total_tags tags with $total_entries entries from " . scalar(@pm_files) . " files\n";
